// 'fields'   => array(
    //     'Donar_age_register'    => $_POST['donarAge'],
    //     'Donar_gender_register'    => $_POST['donargender'],
    //     'Donar_bloodGroup_register'    => $_POST['donarBloodGroup'],
    //     'Donar_presentdivision_register'    => $_POST['donarPresentdivision'],
    //     'Donar_presentdistrict_register'    => $_POST['donarPresentdistrict'],
    //     'Donar_presentzilla_register'    => $_POST['donarPresentzilla'],
    //     'Donar_presentupzilla_register'    => $_POST['donarPresentupzilla'],
    //     'Donar_presentFullAddress_register'    => $_POST['donarPresentFullAddress'],
    //     'Donar_permanentdivision_register'    => $_POST['donarPermanentdivision'],
    //     'Donar_permanentdistrict_register'    => $_POST['donarPermanentdistrict'],
    //     'Donar_permanentzilla_register'    => $_POST['donarPermanentzilla'],
    //     'Donar_permanentupzilla_register'    => $_POST['donarPermanentupzilla'],
    //     'Donar_permanentFullAddress_register'    => $_POST['donarPermanentFullAddress'],
    // ),